

development:
  adapter: postgresql
  encoding: unicode
  database: f3_development
  host: localhost
  pool: 5
  username: f3
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: f3_test
  pool: 5
  username: f3
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: f3_development
  host: localhost
  pool: 5
  username: f3
  password:
